import { mount, flushPromises } from '@vue/test-utils'
import ElementPlus from 'element-plus'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import ProjectBudgetManager from '../src/components/ProjectBudgetManager.vue'
import { calculateBudgetRow, budgetCategories, uppercaseMoney } from '../src/projectBudget'
import type { BudgetLine } from '../src/projectBudget'

const api = vi.hoisted(() => ({ getBudgetAssessments: vi.fn(), getProjectBudget: vi.fn(), saveProjectBudget: vi.fn() }))
vi.mock('../src/api', () => api)
const line = (category: string): BudgetLine => ({ category, budgetAmount: 1000, actualAmount: 100, remainingAmount: 0,
  plannedHours: 10, hourlyRate: 100, actualHours: 1, actualHourlyRate: 100, remainingHours: 0, note: null })
const response = (editable = true) => ({ projectId: 'p1', rows: budgetCategories.filter(category => category.key !== 'RiskReserve').map(category => calculateBudgetRow(line(category.key), null)),
  orders: [], canEdit: editable, canViewReserve: false, rowVersion: 1, updatedAt: null, updatedBy: null })
beforeEach(() => { vi.clearAllMocks(); api.getBudgetAssessments.mockResolvedValue({ sheets: [], amounts: { Standard: 250, MechanicalDesign: 800 } }); api.getProjectBudget.mockResolvedValue(response()); api.saveProjectBudget.mockResolvedValue(response()) })

describe('project budget', () => {
  it('formats Chinese uppercase money across sections and cents', () => {
    expect(uppercaseMoney(900)).toBe('人民币玖佰元整')
    expect(uppercaseMoney(10001000.05)).toBe('人民币壹仟万壹仟元零伍分')
    expect(uppercaseMoney(100000001.10)).toBe('人民币壹亿零壹元壹角')
    expect(uppercaseMoney(0)).toBe('人民币零元整')
    expect(uppercaseMoney(null)).toBe('—')
  })
  it('compares cost sources without duplicating orders and retains unknown values', () => {
    expect(calculateBudgetRow(line('Standard'), 600).estimatedAmount).toBe(600)
    expect(calculateBudgetRow({ ...line('SiteElectrical'), budgetAmount: 1600, hourlyRate: 900, remainingHours: 2 }, null).budgetAmount).toBe(1600)
    expect(calculateBudgetRow({ ...line('SiteElectrical'), hourlyRate: 900, remainingHours: 2 }, null).estimatedAmount).toBe(300)
    expect(calculateBudgetRow({ ...line('SiteElectrical'), actualAmount: 777, actualHours: 90 }, null).actualAmount).toBe(777)
    expect(calculateBudgetRow({ ...line('SiteElectrical'), actualAmount: null }, null).actualAmount).toBeNull()
    expect(calculateBudgetRow({ ...line('Standard'), actualAmount: null }, 600).estimatedAmount).toBeNull()
    expect(calculateBudgetRow(line('Standard'), null, true).alert).toBe('Incomplete')
    expect(calculateBudgetRow({ ...line('SiteElectrical'), remainingHours: 8 }, null).alert).toBe('Warning')
  })
  it('renders four summaries, excludes hidden reserve, and persists manual amounts', async () => {
    const wrapper = mount(ProjectBudgetManager, { props: { project: { id: 'p1' }, token: 'token' }, global: { plugins: [ElementPlus] } })
    await flushPromises()
    expect(wrapper.findAll('.pdm-budget__cards article')).toHaveLength(4)
    expect(wrapper.text()).not.toContain('风险预留')
    expect(wrapper.text()).not.toContain('现场电气工程师调试')
    expect(wrapper.findAll('thead tr')).toHaveLength(2)
    expect(wrapper.find('.pdm-budget__header').exists()).toBe(false)
    expect(wrapper.findAll('.pdm-budget__costs')).toHaveLength(1)
    expect(wrapper.findAll('.pdm-budget__costs .pdm-budget__group')).toHaveLength(2)
    expect(wrapper.find('.pdm-budget__costs .pdm-primary-action').exists()).toBe(true)
    expect(wrapper.findAll('thead th')).toHaveLength(14)
    expect(wrapper.findAll('tfoot tr')).toHaveLength(2)
    expect(wrapper.findAll('tfoot')[0]!.text()).toContain('¥ 5,000.00')
    expect(wrapper.findAll('tfoot')[0]!.text()).toContain('¥ 4,500.00')
    expect(wrapper.findAll('.pdm-budget__cards article')[1]!.text()).toContain('10.0%')
    expect(wrapper.findAll('.pdm-budget__cards article')[2]!.text()).toContain('50.0%')
    expect(wrapper.text()).toContain('剩余工时费用')
    expect(wrapper.find('[aria-label="计划工时"]').exists()).toBe(false)
    expect(wrapper.findAll('input[aria-label="预算金额"]')).toHaveLength(10)
    expect(wrapper.find('.pdm-budget__hint').exists()).toBe(false)
    expect(wrapper.findAll('input[aria-label="实际金额"]')).toHaveLength(10)
    const input = wrapper.find('input[aria-label="预算金额"]')
    await input.setValue('1500')
    await input.trigger('blur')
    await flushPromises()
    const save = wrapper.findAll('button').find(button => button.text().includes('保存预算'))!
    expect(save.attributes('disabled')).toBeUndefined()
    await save.trigger('click')
    await flushPromises()
    expect(api.saveProjectBudget).toHaveBeenCalledWith('p1', expect.objectContaining({ expectedRowVersion: 1, lines: expect.arrayContaining([expect.objectContaining({ category: 'Standard', budgetAmount: 1500 })]) }), 'token')
    wrapper.unmount()
  })
  it('sums entered amounts when other categories are empty', async () => {
    const result = response()
    result.rows = result.rows.map(row => calculateBudgetRow({ ...row.input, budgetAmount: row.input.category === 'Standard' ? 1000 : null, actualAmount: row.input.category === 'Standard' ? 900 : null }, null))
    api.getProjectBudget.mockResolvedValue(result)
    const wrapper = mount(ProjectBudgetManager, { props: { project: { id: 'p1' }, token: 'token' }, global: { plugins: [ElementPlus] } })
    await flushPromises()
    expect(wrapper.findAll('tfoot')[0]!.text()).toContain('¥ 1,000.00')
    expect(wrapper.findAll('tfoot')[0]!.text()).toContain('¥ 900.00')
    expect(wrapper.findAll('tfoot')[0]!.text()).toContain('¥ 100.00')
    expect(wrapper.findAll('.pdm-budget__cards article')[1]!.text()).toContain('90.0%')
    expect(wrapper.findAll('tfoot')[1]!.text()).toContain('未录入')
    wrapper.unmount()
  })
  it('lets finance enter actual hours and amounts without editing budgets', async () => {
    api.getProjectBudget.mockResolvedValue({ ...response(), canEditBudget: false, canEditActual: true })
    const wrapper = mount(ProjectBudgetManager, { props: { project: { id: 'p1' }, token: 'token' }, global: { plugins: [ElementPlus] } })
    await flushPromises()
    expect(wrapper.find('input[aria-label="预算金额"]').attributes('disabled')).toBeDefined()
    const input = wrapper.findAll('input[aria-label="实际金额"]')[5]!
    await input.setValue('777')
    await input.trigger('blur')
    await wrapper.findAll('button').find(button => button.text().includes('保存预算'))!.trigger('click')
    await flushPromises()
    expect(api.saveProjectBudget).toHaveBeenCalledWith('p1', expect.objectContaining({ lines: expect.arrayContaining([expect.objectContaining({ category: 'MechanicalDesign', actualAmount: 777, actualHours: 1 })]) }), 'token')
    wrapper.unmount()
  })
  it('renders a read only view for viewers and reports denied access', async () => {
    api.getProjectBudget.mockResolvedValue(response(false))
    const wrapper = mount(ProjectBudgetManager, { props: { project: { id: 'p1' }, token: 'token' }, global: { plugins: [ElementPlus] } })
    await flushPromises()
    expect(wrapper.text()).not.toContain('保存预算')
    expect(wrapper.findAll('input').every(input => input.attributes('disabled') !== undefined)).toBe(true)
    api.getProjectBudget.mockRejectedValue(new Error('没有预算查看权限'))
    await wrapper.setProps({ project: { id: 'p2' } })
    await flushPromises()
    expect(wrapper.text()).toContain('没有预算查看权限')
    expect(wrapper.findAll('.pdm-budget__cards article')).toHaveLength(0)
    wrapper.unmount()
  })
})
