CREATE TABLE IF NOT EXISTS role_permission (
    role_code VARCHAR(40) NOT NULL,
    permission_code VARCHAR(100) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (role_code,permission_code),
    KEY ix_role_permission_code (permission_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT IGNORE INTO role_permission(role_code,permission_code,updated_at) VALUES
('Engineer','project.view',UTC_TIMESTAMP(6)),
('Engineer','project.create',UTC_TIMESTAMP(6)),
('Engineer','project.child.create',UTC_TIMESTAMP(6)),
('Engineer','project.staffing.manage',UTC_TIMESTAMP(6)),
('Engineer','project.designer.assign',UTC_TIMESTAMP(6)),
('Engineer','project.content.view',UTC_TIMESTAMP(6)),
('Engineer','document.edit',UTC_TIMESTAMP(6)),
('Engineer','bom.edit',UTC_TIMESTAMP(6)),
('Engineer','release.manage',UTC_TIMESTAMP(6)),
('PlanningManager','project.view',UTC_TIMESTAMP(6)),
('PlanningManager','project.execution.assign',UTC_TIMESTAMP(6)),
('ProcessReviewer','project.view',UTC_TIMESTAMP(6)),
('ProcessReviewer','project.content.view',UTC_TIMESTAMP(6)),
('ProcessReviewer','approval.decide',UTC_TIMESTAMP(6)),
('Approver','project.view',UTC_TIMESTAMP(6)),
('Approver','project.content.view',UTC_TIMESTAMP(6)),
('Approver','approval.decide',UTC_TIMESTAMP(6)),
('ProductionViewer','project.view',UTC_TIMESTAMP(6)),
('ProductionViewer','project.content.view',UTC_TIMESTAMP(6)),
('Administrator','project.view',UTC_TIMESTAMP(6)),
('Administrator','project.create',UTC_TIMESTAMP(6)),
('Administrator','project.child.create',UTC_TIMESTAMP(6)),
('Administrator','project.delete',UTC_TIMESTAMP(6)),
('Administrator','project.execution.assign',UTC_TIMESTAMP(6)),
('Administrator','project.staffing.manage',UTC_TIMESTAMP(6)),
('Administrator','project.designer.assign',UTC_TIMESTAMP(6)),
('Administrator','project.content.view',UTC_TIMESTAMP(6)),
('Administrator','document.edit',UTC_TIMESTAMP(6)),
('Administrator','bom.edit',UTC_TIMESTAMP(6)),
('Administrator','release.manage',UTC_TIMESTAMP(6)),
('Administrator','approval.decide',UTC_TIMESTAMP(6)),
('Administrator','settings.customer.manage',UTC_TIMESTAMP(6)),
('Administrator','settings.organization.manage',UTC_TIMESTAMP(6)),
('Administrator','settings.folder.manage',UTC_TIMESTAMP(6)),
('Administrator','settings.storage.manage',UTC_TIMESTAMP(6)),
('Administrator','system.role.view',UTC_TIMESTAMP(6)),
('Administrator','system.role.edit',UTC_TIMESTAMP(6)),
('Administrator','audit.view',UTC_TIMESTAMP(6));
