CREATE TABLE drawing_review_package (
    id BINARY(16) NOT NULL PRIMARY KEY,
    project_id BINARY(16) NOT NULL,
    review_number VARCHAR(80) NOT NULL,
    state VARCHAR(40) NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    approved_at DATETIME(6) NULL,
    UNIQUE KEY ux_drawing_review_number (review_number),
    KEY ix_drawing_review_project_state (project_id,state,created_at),
    CONSTRAINT fk_drawing_review_project FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE drawing_review_item (
    id BINARY(16) NOT NULL PRIMARY KEY,
    package_id BINARY(16) NOT NULL,
    bom_item_id BINARY(16) NOT NULL,
    drawing_number VARCHAR(160) NOT NULL,
    item_name VARCHAR(300) NOT NULL,
    source_configuration VARCHAR(160) NULL,
    model_document_id BINARY(16) NOT NULL,
    model_version_id BINARY(16) NOT NULL,
    model_revision VARCHAR(20) NOT NULL,
    model_sha256 CHAR(64) NOT NULL,
    model_created_by VARCHAR(100) NOT NULL,
    drawing_document_id BINARY(16) NOT NULL,
    drawing_version_id BINARY(16) NOT NULL,
    drawing_revision VARCHAR(20) NOT NULL,
    drawing_sha256 CHAR(64) NOT NULL,
    drawing_created_by VARCHAR(100) NOT NULL,
    model_state VARCHAR(40) NOT NULL,
    model_reviewer VARCHAR(100) NULL,
    model_reviewer_name VARCHAR(160) NULL,
    model_reviewed_at DATETIME(6) NULL,
    model_comment VARCHAR(2000) NULL,
    drawing_state VARCHAR(40) NOT NULL,
    drawing_reviewer VARCHAR(100) NULL,
    drawing_reviewer_name VARCHAR(160) NULL,
    drawing_reviewed_at DATETIME(6) NULL,
    drawing_comment VARCHAR(2000) NULL,
    model_writeback_id BINARY(16) NULL,
    drawing_writeback_id BINARY(16) NULL,
    model_result_version_id BINARY(16) NULL,
    drawing_result_version_id BINARY(16) NULL,
    UNIQUE KEY ux_drawing_review_item_bom (package_id,bom_item_id),
    KEY ix_drawing_review_item_model (model_document_id,model_version_id),
    KEY ix_drawing_review_item_drawing (drawing_document_id,drawing_version_id),
    KEY ix_drawing_review_item_writeback_model (model_writeback_id),
    KEY ix_drawing_review_item_writeback_drawing (drawing_writeback_id),
    CONSTRAINT fk_drawing_review_item_package FOREIGN KEY (package_id) REFERENCES drawing_review_package(id) ON DELETE CASCADE,
    CONSTRAINT fk_drawing_review_item_model_document FOREIGN KEY (model_document_id) REFERENCES document(id),
    CONSTRAINT fk_drawing_review_item_model_version FOREIGN KEY (model_version_id) REFERENCES document_version(id),
    CONSTRAINT fk_drawing_review_item_drawing_document FOREIGN KEY (drawing_document_id) REFERENCES document(id),
    CONSTRAINT fk_drawing_review_item_drawing_version FOREIGN KEY (drawing_version_id) REFERENCES document_version(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE drawing_review_markup (
    id BINARY(16) NOT NULL PRIMARY KEY,
    package_id BINARY(16) NOT NULL,
    item_id BINARY(16) NOT NULL,
    target VARCHAR(30) NOT NULL,
    view_name VARCHAR(160) NULL,
    normalized_x DECIMAL(8,6) NULL,
    normalized_y DECIMAL(8,6) NULL,
    markup_text VARCHAR(2000) NOT NULL,
    severity VARCHAR(30) NOT NULL,
    state VARCHAR(30) NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    resolved_by VARCHAR(100) NULL,
    resolved_at DATETIME(6) NULL,
    KEY ix_drawing_review_markup_item (item_id,target,state),
    CONSTRAINT fk_drawing_review_markup_package FOREIGN KEY (package_id) REFERENCES drawing_review_package(id) ON DELETE CASCADE,
    CONSTRAINT fk_drawing_review_markup_item FOREIGN KEY (item_id) REFERENCES drawing_review_item(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT IGNORE INTO role_permission(role_code,permission_code,updated_at) VALUES
('Engineer','drawing-review.submit',UTC_TIMESTAMP(6)),
('Engineer','drawing-review.annotate',UTC_TIMESTAMP(6)),
('ProcessReviewer','drawing-review.annotate',UTC_TIMESTAMP(6)),
('ProcessReviewer','drawing-review.decide',UTC_TIMESTAMP(6)),
('Approver','drawing-review.annotate',UTC_TIMESTAMP(6)),
('Approver','drawing-review.decide',UTC_TIMESTAMP(6)),
('BusinessUnitManager','drawing-review.annotate',UTC_TIMESTAMP(6)),
('BusinessUnitManager','drawing-review.decide',UTC_TIMESTAMP(6)),
('Administrator','drawing-review.submit',UTC_TIMESTAMP(6)),
('Administrator','drawing-review.annotate',UTC_TIMESTAMP(6)),
('Administrator','drawing-review.decide',UTC_TIMESTAMP(6));
